// ══════════════════════════════════════════════════════════════════════
// Portable file storage — the file counterpart of db.ts.
//
//   STORAGE_DRIVER=supabase (default)  Supabase Storage via its REST API
//   STORAGE_DRIVER=local               files on disk under FILE_STORAGE_DIR
//                                      (default local/storage), served by the
//                                      backend at <ORCH_SELF_URL>/files/<bucket>/<name>
//
// Stored file URLs are absolute, like Supabase public URLs, so code that
// fetches or links a file_url works the same with either driver.
// ══════════════════════════════════════════════════════════════════════

const DRIVER       = (Deno.env.get('STORAGE_DRIVER') || 'supabase').toLowerCase()
const SUPABASE_URL = Deno.env.get('SUPABASE_URL') || ''
const SUPABASE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || ''
const STORAGE_DIR  = (Deno.env.get('FILE_STORAGE_DIR') || 'local/storage').replace(/[\\/]+$/, '')
const SELF_URL     = (Deno.env.get('ORCH_SELF_URL') || '').replace(/\/+$/, '')

if (DRIVER !== 'supabase' && DRIVER !== 'local') {
  throw new Error(`STORAGE_DRIVER must be "supabase" or "local", got "${DRIVER}"`)
}
if (DRIVER === 'local' && !SELF_URL) {
  throw new Error('STORAGE_DRIVER=local needs ORCH_SELF_URL (the URL file links are built from)')
}

export const USE_LOCAL_STORAGE = DRIVER === 'local'
export const BUCKETS = ['documents', 'review-files']
export const MAX_FILE_BYTES = 50 * 1024 * 1024

const TYPES: Record<string, string> = {
  pdf: 'application/pdf', png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp',
  txt: 'text/plain; charset=utf-8', csv: 'text/csv; charset=utf-8', json: 'application/json',
  doc: 'application/msword', docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xls: 'application/vnd.ms-excel', xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
}

// Types a browser may display in place. Everything else — HTML and SVG
// included — is served as a download, so an uploaded page never runs on the
// backend's origin.
export const INLINE_TYPES = new Set(['application/pdf', 'image/png', 'image/jpeg', 'image/gif', 'image/webp', 'text/plain; charset=utf-8'])

export function contentTypeFor(name: string): string {
  return TYPES[(name.split('.').pop() || '').toLowerCase()] || 'application/octet-stream'
}

// Object names are generated by objectName(): only [A-Za-z0-9._-], so they
// can never escape the bucket directory.
export function isValidName(name: string): boolean {
  return /^[A-Za-z0-9._-]{1,200}$/.test(name) && !name.startsWith('.')
}

export function objectName(originalName: string): string {
  const safe = originalName.replace(/[^a-zA-Z0-9._-]/g, '_').slice(-120) || 'file'
  return `${Date.now()}_${crypto.randomUUID().slice(0, 8)}_${safe}`
}

export function publicUrl(bucket: string, name: string): string {
  return USE_LOCAL_STORAGE
    ? `${SELF_URL}/files/${bucket}/${name}`
    : `${SUPABASE_URL}/storage/v1/object/public/${bucket}/${name}`
}

// The object name inside a URL built by publicUrl() (either driver), or null
export function nameFromUrl(bucket: string, url: string): string | null {
  const m = String(url || '').match(new RegExp(`/${bucket}/([^/?#]+)$`))
  if (!m) return null
  let name = ''
  try { name = decodeURIComponent(m[1]) } catch { return null }
  return isValidName(name) ? name : null
}

export async function putFile(bucket: string, name: string, data: Uint8Array<ArrayBuffer>, contentType: string): Promise<void> {
  if (USE_LOCAL_STORAGE) {
    await Deno.mkdir(`${STORAGE_DIR}/${bucket}`, { recursive: true })
    await Deno.writeFile(`${STORAGE_DIR}/${bucket}/${name}`, data, { createNew: true })
    return
  }
  const r = await fetch(`${SUPABASE_URL}/storage/v1/object/${bucket}/${name}`, {
    method: 'POST',
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}`, 'Content-Type': contentType, 'x-upsert': 'false' },
    body: data,
  })
  if (!r.ok) throw new Error(`storage upload failed: ${r.status} ${await r.text()}`)
}

// Local driver only (Supabase serves its public URLs itself). null when missing.
export async function readFile(bucket: string, name: string): Promise<Uint8Array<ArrayBuffer> | null> {
  try {
    return await Deno.readFile(`${STORAGE_DIR}/${bucket}/${name}`)
  } catch (e) {
    if (e instanceof Deno.errors.NotFound) return null
    throw e
  }
}

// A missing file is not an error
export async function deleteFile(bucket: string, name: string): Promise<void> {
  if (USE_LOCAL_STORAGE) {
    try {
      await Deno.remove(`${STORAGE_DIR}/${bucket}/${name}`)
    } catch (e) {
      if (!(e instanceof Deno.errors.NotFound)) throw e
    }
    return
  }
  const r = await fetch(`${SUPABASE_URL}/storage/v1/object/${bucket}`, {
    method: 'DELETE',
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ prefixes: [name] }),
  })
  if (!r.ok) throw new Error(`storage delete failed: ${r.status}`)
}
