// ══════════════════════════════════════════════════════════════════════
// Portable file storage — the file counterpart of db.ts.
//
//   STORAGE_DRIVER=supabase (default)  Supabase Storage via its REST API
//   STORAGE_DRIVER=local               files on disk under FILE_STORAGE_DIR
//                                      (default local/storage), served by the
//                                      backend at <ORCH_SELF_URL>/files/<bucket>/<name>
//
// Stored file URLs are absolute, like Supabase public URLs, so code that
// fetches or links a file_url works the same with either driver.
// ══════════════════════════════════════════════════════════════════════

const DRIVER       = (Deno.env.get('STORAGE_DRIVER') || 'supabase').toLowerCase()
const SUPABASE_URL = Deno.env.get('SUPABASE_URL') || ''
const SUPABASE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || ''
const STORAGE_DIR  = (Deno.env.get('FILE_STORAGE_DIR') || 'local/storage').replace(/[\\/]+$/, '')
const SELF_URL     = (Deno.env.get('ORCH_SELF_URL') || '').replace(/\/+$/, '')

if (DRIVER !== 'supabase' && DRIVER !== 'local') {
  throw new Error(`STORAGE_DRIVER must be "supabase" or "local", got "${DRIVER}"`)
}
if (DRIVER === 'local' && !SELF_URL) {
  throw new Error('STORAGE_DRIVER=local needs ORCH_SELF_URL (the URL file links are built from)')
}
// Download links are time-limited and HMAC-signed with the backend's internal secret
const URL_SECRET = Deno.env.get('ORCH_INTERNAL_SECRET') || ''
if (DRIVER === 'local' && !URL_SECRET) {
  throw new Error('STORAGE_DRIVER=local needs ORCH_INTERNAL_SECRET (download links are signed with it)')
}

export const USE_LOCAL_STORAGE = DRIVER === 'local'
export const BUCKETS = ['documents', 'review-files']
export const MAX_FILE_BYTES = 50 * 1024 * 1024

const TYPES: Record<string, string> = {
  pdf: 'application/pdf', png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp',
  txt: 'text/plain; charset=utf-8', csv: 'text/csv; charset=utf-8', json: 'application/json',
  doc: 'application/msword', docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xls: 'application/vnd.ms-excel', xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
}

// Types a browser may display in place. Everything else — HTML and SVG
// included — is served as a download, so an uploaded page never runs on the
// backend's origin.
export const INLINE_TYPES = new Set(['application/pdf', 'image/png', 'image/jpeg', 'image/gif', 'image/webp', 'text/plain; charset=utf-8'])

export function contentTypeFor(name: string): string {
  return TYPES[(name.split('.').pop() || '').toLowerCase()] || 'application/octet-stream'
}

// Object names are generated by objectName(): only [A-Za-z0-9._-], so they
// can never escape the bucket directory.
export function isValidName(name: string): boolean {
  return /^[A-Za-z0-9._-]{1,200}$/.test(name) && !name.startsWith('.')
}

export function objectName(originalName: string): string {
  const safe = originalName.replace(/[^a-zA-Z0-9._-]/g, '_').slice(-120) || 'file'
  return `${Date.now()}_${crypto.randomUUID().slice(0, 8)}_${safe}`
}

export function publicUrl(bucket: string, name: string): string {
  return USE_LOCAL_STORAGE
    ? `${SELF_URL}/files/${bucket}/${name}`
    : `${SUPABASE_URL}/storage/v1/object/public/${bucket}/${name}`
}

// The object name inside a URL built by publicUrl() (either driver), or null
export function nameFromUrl(bucket: string, url: string): string | null {
  const m = String(url || '').match(new RegExp(`/${bucket}/([^/?#]+)$`))
  if (!m) return null
  let name = ''
  try { name = decodeURIComponent(m[1]) } catch { return null }
  return isValidName(name) ? name : null
}

export async function putFile(bucket: string, name: string, data: Uint8Array<ArrayBuffer>, contentType: string): Promise<void> {
  if (USE_LOCAL_STORAGE) {
    await Deno.mkdir(`${STORAGE_DIR}/${bucket}`, { recursive: true })
    await Deno.writeFile(`${STORAGE_DIR}/${bucket}/${name}`, data, { createNew: true })
    return
  }
  const r = await fetch(`${SUPABASE_URL}/storage/v1/object/${bucket}/${name}`, {
    method: 'POST',
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}`, 'Content-Type': contentType, 'x-upsert': 'false' },
    body: data,
  })
  if (!r.ok) throw new Error(`storage upload failed: ${r.status} ${await r.text()}`)
}

// Local driver only (Supabase serves its public URLs itself). null when missing.
export async function readFile(bucket: string, name: string): Promise<Uint8Array<ArrayBuffer> | null> {
  try {
    return await Deno.readFile(`${STORAGE_DIR}/${bucket}/${name}`)
  } catch (e) {
    if (e instanceof Deno.errors.NotFound) return null
    throw e
  }
}

async function hmacHex(message: string): Promise<string> {
  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(URL_SECRET), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign'])
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(message))
  return [...new Uint8Array(sig)].map(b => b.toString(16).padStart(2, '0')).join('')
}

// A time-limited download link for a stored file URL (as built by publicUrl).
// Local driver: an HMAC-signed query the download route checks. Supabase driver:
// Supabase's own signed URL — it only protects files if the bucket is private.
// A URL that is not one of ours is returned unchanged.
export async function signedUrl(url: string | null | undefined, ttlSeconds: number): Promise<string | null> {
  if (!url) return url ?? null
  for (const bucket of BUCKETS) {
    const name = nameFromUrl(bucket, url)
    if (!name) continue
    if (USE_LOCAL_STORAGE) {
      const exp = Math.floor(Date.now() / 1000) + ttlSeconds
      return `${publicUrl(bucket, name)}?exp=${exp}&sig=${await hmacHex(`${bucket}/${name}:${exp}`)}`
    }
    const r = await fetch(`${SUPABASE_URL}/storage/v1/object/sign/${bucket}/${name}`, {
      method: 'POST',
      headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ expiresIn: ttlSeconds }),
    })
    if (!r.ok) return url
    const { signedURL } = await r.json() as { signedURL?: string }
    return signedURL ? `${SUPABASE_URL}/storage/v1${signedURL}` : url
  }
  return url
}

// Local driver: is this download link's signature valid and unexpired?
export async function verifySignedDownload(bucket: string, name: string, exp: string | null, sig: string | null): Promise<boolean> {
  if (!URL_SECRET || !exp || !sig || !/^\d+$/.test(exp) || Number(exp) < Date.now() / 1000) return false
  const expected = await hmacHex(`${bucket}/${name}:${exp}`)
  if (expected.length !== sig.length) return false
  let diff = 0
  for (let i = 0; i < expected.length; i++) diff |= expected.charCodeAt(i) ^ sig.charCodeAt(i)
  return diff === 0
}

// A missing file is not an error
export async function deleteFile(bucket: string, name: string): Promise<void> {
  if (USE_LOCAL_STORAGE) {
    try {
      await Deno.remove(`${STORAGE_DIR}/${bucket}/${name}`)
    } catch (e) {
      if (!(e instanceof Deno.errors.NotFound)) throw e
    }
    return
  }
  const r = await fetch(`${SUPABASE_URL}/storage/v1/object/${bucket}`, {
    method: 'DELETE',
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ prefixes: [name] }),
  })
  if (!r.ok) throw new Error(`storage delete failed: ${r.status}`)
}
